package agent

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

func (d *DNSConfigurator) getActiveDNS() (iface string, dns []string, err error) {
	// Read current resolv.conf
	data, err := os.ReadFile("/etc/resolv.conf")
	if err != nil {
		return "resolv.conf", nil, fmt.Errorf("read resolv.conf: %w", err)
	}

	var servers []string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "nameserver ") {
			ns := strings.TrimPrefix(line, "nameserver ")
			ns = strings.TrimSpace(ns)
			if ns != "" && ns != "127.0.0.1" {
				servers = append(servers, ns)
			}
		}
	}

	return "resolv.conf", servers, nil
}

func (d *DNSConfigurator) setDNS(iface string, servers []string) error {
	// Check if resolvconf is available
	if _, err := exec.LookPath("resolvconf"); err == nil {
		return d.setDNSResolvconf(servers)
	}

	// Fallback: directly write /etc/resolv.conf
	return d.setDNSDirectly(servers)
}

func (d *DNSConfigurator) resetDNS(iface string) error {
	if len(d.originalDNS) == 0 {
		// Restore to common defaults
		d.originalDNS = []string{"8.8.8.8", "1.1.1.1"}
	}
	return d.setDNS(iface, d.originalDNS)
}

func (d *DNSConfigurator) setDNSResolvconf(servers []string) error {
	var content strings.Builder
	for _, s := range servers {
		content.WriteString("nameserver " + s + "\n")
	}

	cmd := exec.Command("resolvconf", "-a", "biglybigly")
	cmd.Stdin = strings.NewReader(content.String())
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("resolvconf: %w — %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

func (d *DNSConfigurator) setDNSDirectly(servers []string) error {
	var content strings.Builder
	content.WriteString("# Generated by biglybigly agent — will be restored on shutdown\n")
	for _, s := range servers {
		content.WriteString("nameserver " + s + "\n")
	}

	if err := os.WriteFile("/etc/resolv.conf", []byte(content.String()), 0644); err != nil {
		return fmt.Errorf("write resolv.conf: %w", err)
	}
	return nil
}
