package agent

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

// getActiveDNS reads /etc/resolv.conf and returns the list of upstream
// nameservers (excluding 127.0.0.1, which would indicate the agent is
// already in place). The returned "interface" is the symbolic value
// "resolv.conf" since Linux configures DNS at the file level rather
// than per-adapter.
func (d *DNSConfigurator) getActiveDNS() (iface string, dns []string, err error) {
	data, err := os.ReadFile("/etc/resolv.conf")
	if err != nil {
		return "resolv.conf", nil, fmt.Errorf("read resolv.conf: %w", err)
	}

	var servers []string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "nameserver ") {
			ns := strings.TrimPrefix(line, "nameserver ")
			ns = strings.TrimSpace(ns)
			// Skip 127.0.0.1 so a stale agent config doesn't get
			// recorded as the "original" resolver.
			if ns != "" && ns != "127.0.0.1" {
				servers = append(servers, ns)
			}
		}
	}

	return "resolv.conf", servers, nil
}

// setDNS prefers resolvconf when it is available so the change is
// integrated with the system's resolver management; otherwise it falls
// back to overwriting /etc/resolv.conf directly.
func (d *DNSConfigurator) setDNS(iface string, servers []string) error {
	if _, err := exec.LookPath("resolvconf"); err == nil {
		return d.setDNSResolvconf(servers)
	}
	return d.setDNSDirectly(servers)
}

// resetDNS on Linux has no "automatic" path (resolv.conf has no concept
// of DHCP-managed DNS), so we fall back to well-known public resolvers
// when the original list is unknown.
func (d *DNSConfigurator) resetDNS(iface string) error {
	if len(d.originalDNS) == 0 {
		d.originalDNS = []string{"8.8.8.8", "1.1.1.1"}
	}
	return d.setDNS(iface, d.originalDNS)
}

// setDNSResolvconf installs the given servers under the "biglybigly"
// resolvconf tag.
func (d *DNSConfigurator) setDNSResolvconf(servers []string) error {
	var content strings.Builder
	for _, s := range servers {
		content.WriteString("nameserver " + s + "\n")
	}

	cmd := exec.Command("resolvconf", "-a", "biglybigly")
	cmd.Stdin = strings.NewReader(content.String())
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("resolvconf: %w — %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// setDNSDirectly overwrites /etc/resolv.conf in place. The original
// contents are preserved in memory by the DNSConfigurator and reapplied
// by Restore on shutdown.
func (d *DNSConfigurator) setDNSDirectly(servers []string) error {
	var content strings.Builder
	content.WriteString("# Generated by biglybigly agent — will be restored on shutdown\n")
	for _, s := range servers {
		content.WriteString("nameserver " + s + "\n")
	}

	if err := os.WriteFile("/etc/resolv.conf", []byte(content.String()), 0644); err != nil {
		return fmt.Errorf("write resolv.conf: %w", err)
	}
	return nil
}
